CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "User" (
  id SERIAL PRIMARY KEY,
  email CITEXT COLLATE "ucs_basic" UNIQUE NOT NULL,
  password VARCHAR(256) NOT NULL,
  nickname CITEXT COLLATE "ucs_basic" UNIQUE NOT NULL,
  rating INTEGER DEFAULT 0
);